version: '2'
services:
  website_app:
    build: ./environment/containers/website_app
    container_name: website_app
    volumes:
      - .:/var/www/html
      - ./logs/app:/var/log/httpd
    environment:
      - VIRTUAL_HOST=local.mydevsite.com
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - HTTPS_METHOD=redirect
    env_file: .env
    network_mode: "bridge"
    extra_hosts:
      - "local.mydevsite.com:127.0.0.1"